apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rag-chatbot
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: https://github.com/Anant1213/rag-prod.git
    targetRevision: main
    path: deploy/helm/rag-chatbot
    helm:
      valueFiles: [values.yaml]
  destination:
    server: https://kubernetes.default.svc
    namespace: rag
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true]
    retry:
      limit: 3
      backoff: {duration: 10s, factor: 2, maxDuration: 3m}
